---
- name: Create caddy dir
  file:
    path: $HOME/caddy
    state: directory

- name: Copy caddy conf
  template:
    src: Caddyfile.j2
    dest: ~/caddy/Caddyfile

- name: Copy caddy docker-compose
  copy:
    src: docker-compose.yml
    dest: ~/caddy/docker-compose.yml

- name: Check if caddy is running
  shell: docker ps | grep caddy |  cut -d ' ' -f 1
  register: caddy_id

- name: Start caddy
  shell: cd $HOME/caddy && docker-compose up -d
  when: caddy_id.stdout == ""

- name: Reload caddy
  shell: docker exec -w /etc/caddy {{ caddy_id.stdout }} caddy reload
  when: caddy_id.stdout != ""
