---
- name: Create filebrowser work dir
  file:
    path: $HOME/filebrowser
    state: directory

- name: Copy filebrowser docker-compose
  copy:
    src: docker-compose.yml
    dest: $HOME/filebrowser/docker-compose.yml

- name: Create data dir
  become: yes
  file:
    path: /data
    state: directory

- name: Set data dir ACL
  become: yes
  shell: setfacl -m u:1000:rwx -Rd /data && setfacl -m g:1000:rwx -Rd /data

- name: Check if database file exists
  stat: path=$HOME/filebrowser/database.db
  register: p

- name: Create filebrowser database file
  file:
    path: $HOME/filebrowser/database.db
    state: touch
  when: p.stat.exists == False

- name: Start filebrowser
  shell: cd $HOME/filebrowser && docker-compose up -d
