---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=3001
      - TORRENTING_PORT=6881
    volumes:
      - $HOME/torrent:/config
      - /data:/downloads
    ports:
      - 3001:3001
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped