version: "3.8"

services:
  caddy:
    image: caddy
    container_name: caddy
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "4443:4443"
    volumes:
      - $HOME/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /var/www/:/var/www
