version: "3.8"
services:
  caddy:
    image: caddy
    container_name: caddy
    restart: unless-stopped
    volumes:
      - $HOME/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /var/www/:/var/www
      - /data:/downloads
    network_mode: host