version: '3.8'
services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    restart: always
    user: 1000:1000
    volumes:
      - /data:/srv
      - $HOME/filebrowser/database.db:/database.db
    ports:
      - 8888:80
