version: '3.8'
services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    restart: always
    volumes:
      - /filebrowser/data:/srv
      - /filebrowser/db/database.db:/database.db
    ports:
      - 8888:80
