---
- name: Setup server
  hosts: vps
  roles:
    - mosh
    - docker

- name: Setup drone
  hosts: vps
  roles:
    - drone

- name: Setup caddy
  hosts: vps
  roles:
    - caddy

- name: Setup user for www uploads
  hosts: vps
  roles:
    - uploads

- name: Setup filebrowser
  hosts: vps
  roles:
    - filebrowser

- name: Setup torrent
  hosts: vps
  roles:
    - torrent
