---
- name: Setup docker
  hosts: vps
  roles:
    - docker

- name: Setup drone
  hosts: vps
  roles:
    - drone

- name: Setup caddy
  hosts: vps
  roles:
    - caddy

- name: Setup user for www uploads
  hosts: vps
  roles:
    - uploads

- name: Setup filebrowser
  hosts: vps
  roles:
    - filebrowser
