version: '3.8'
services:
  drone-server:
    container_name: drone-server
    image: drone/drone:linux-arm64
    restart: always
    environment:
      - DRONE_GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID
      - DRONE_GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET
      - DRONE_RPC_SECRET=$DRONE_RPC_SECRET
      - DRONE_SERVER_HOST=drone.$HOSTNAME
      - DRONE_SERVER_PROTO=http
    ports:
      - 6666:80

  drone-runner:
    container_name: drone-runner
    image: drone/drone-runner-docker:linux-arm64
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_SECRET=$DRONE_RPC_SECRET
      - DRONE_RUNNER_CAPACITY=4
    ports:
      - 3000:3000
